import type { Product } from '@/types';

export const products: Product[] = [
  {
    id: 'prod_001',
    name: 'Organic Apples',
    category: 'Fresh Produce',
    price: 2.99,
    imageUrl: 'https://placehold.co/300x300.png',
    stock: 150,
  },
  {
    id: 'prod_002',
    name: 'Ripe Bananas',
    category: 'Fresh Produce',
    price: 1.49,
    imageUrl: 'https://placehold.co/300x300.png',
    stock: 200,
  },
  {
    id: 'prod_003',
    name: 'Sourdough Bread',
    category: 'Bakery',
    price: 5.49,
    imageUrl: 'https://placehold.co/300x300.png',
    stock: 50,
  },
  {
    id: 'prod_004',
    name: 'Butter Croissant',
    category: 'Bakery',
    price: 3.25,
    imageUrl: 'https://placehold.co/300x300.png',
    stock: 80,
  },
  {
    id: 'prod_005',
    name: 'Whole Milk',
    category: 'Dairy',
    price: 3.89,
    imageUrl: 'https://placehold.co/300x300.png',
    stock: 100,
  },
  {
    id: 'prod_006',
    name: 'Cheddar Cheese Block',
    category: 'Dairy',
    price: 6.99,
    imageUrl: 'https://placehold.co/300x300.png',
    stock: 75,
  },
  {
    id: 'prod_007',
    name: 'Kettle-Cooked Chips',
    category: 'Snacks',
    price: 4.79,
    imageUrl: 'https://placehold.co/300x300.png',
    stock: 120,
  },
  {
    id: 'prod_008',
    name: 'Dark Chocolate Bar',
    category: 'Snacks',
    price: 3.99,
    imageUrl: 'https://placehold.co/300x300.png',
    stock: 90,
  },
  {
    id: 'prod_009',
    name: 'Avocado',
    category: 'Fresh Produce',
    price: 1.99,
    imageUrl: 'https://placehold.co/300x300.png',
    stock: 110,
  },
  {
    id: 'prod_010',
    name: 'Baguette',
    category: 'Bakery',
    price: 2.79,
    imageUrl: 'https://placehold.co/300x300.png',
    stock: 60,
  },
  {
    id: 'prod_011',
    name: 'Greek Yogurt',
    category: 'Dairy',
    price: 4.49,
    imageUrl: 'https://placehold.co/300x300.png',
    stock: 85,
  },
  {
    id: 'prod_012',
    name: 'Salted Pretzels',
    category: 'Snacks',
    price: 3.29,
    imageUrl: 'https://placehold.co/300x300.png',
    stock: 150,
  },
];
